# Deep independent V-L Prompting
DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
  TEST:
    BATCH_SIZE: 256
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

OPTIM:
  NAME: "adadelta"
  LR: 0.15
  MAX_EPOCH: 5
  WEIGHT_DECAY: 0.001
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "linear"
  WARMUP_CONS_LR: 1e-2
  WARMUP_MIN_LR : 1e-2


TRAIN:
  PRINT_FREQ: 20

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  APEX:
    N_CTX_VISION: 2
    N_CTX_TEXT: 2
    CTX_INIT: "a photo of a #."
    PREC: "fp16"
    PROMPT_DEPTH_VISION: 12
    PROMPT_DEPTH_TEXT: 1